<div class="content">
    <?php
    if($this->isEnabled() == true) : ?>
    <div name="helloworld_content">
        <?php echo $this->__('Zend to Magento');
            echo "<hr>";
            echo $this->__('Attempt');
             echo "<hr>";
        if($this->getMessage()!="")
            echo $this->getMessage();
        else
            echo $this->__('Have you written something?');
        ?>
    </div>
    <?php endif ; ?>
</div>